spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  data:
    redis:
      host: localhost
      port: 6370 # Different port for test
  
  kafka:
    bootstrap-servers: localhost:9093 # Different port for test

# Test configuration
exchange:
  binance:
    base-url: http://localhost:8080/mock-binance
  coinbase:
    base-url: http://localhost:8080/mock-coinbase

data-collection:
  symbols:
    - BTCUSDT
  intervals:
    - 1m
  fetch-interval: 60000
  cache-ttl: 10

logging:
  level:
    com.cryptotrading: DEBUG
